### ISSUE TITLE
Brooks's law / Law of diminishing returns

### ISSUE THREAD

**Issue by laurentenhoor** [deepkanwal/mentalmodelsbox-data#1]
What do you think of adding Brooks's law?
https://en.wikipedia.org/wiki/Brooks%27s_law

**Comment by deepkanwal** [comment]
Great idea--thanks for suggesting. Added it [here](https://github.com/deepkanwal/mentalmodelsbox-data/blob/master/18-diminishing-returns.yml), feel free to update.
